### PR TITLE
Fix channel_name and install_from metric names doesn't match.

### LINKED ISSUE #202: `install_from` and `channel_name` metrics are null strings when doing query
**Environment (please complete the following information):**
The telemetry result from [FxR dashboard](https://sql.telemetry.mozilla.org/dashboard/firefox-reality-pc).

**Describe the bug**
I checked our call stack, we do set proper values into Glean via its interfaces. and the [Ping debug viewer](https://debug-ping-preview.firebaseapp.com/pings/dmu) also tells us our metrics string are
```
"metrics": {"string":{"distribution.ff_install_from":"embedded",
"distribution.fxr_channel_name":"htc",
"launch.entry_method":"library"}}
```

According to our [ManualMetric](https://github.com/MozillaReality/FirefoxRealityPC/blob/26d2e6a85a69adaf60491e88bd9cd5219012af4a/Source/FirefoxRealityUnity/Assets/Scripts/FxRManualMetrics.cs#L27-L51), our metric name matches to the string we saw in [Ping debug viewer](https://debug-ping-preview.firebaseapp.com/pings/dmu).

However, when querying the metric of `distribution.fxr_channel_name` from our data table (https://sql.telemetry.mozilla.org/queries/75451/source#188352), it tells us we don't have this type in the structure, and it suggests us using `channel_name`. But, using `channel_name`, we are only able to see a null string.

**To Reproduce**
1. Check the query result from the telemetry result from [FxR dashboard](https://sql.telemetry.mozilla.org/dashboard/firefox-reality-pc).

**Expected behavior**
The `install_from` should be `embedded`, and `channel_name` should be `htc`.

### PR DESCRIPTION
**Pull request by daoshengmu**
Fixes #202.

We have to make the metrics category/names as declared in the ManualMetrics.cs match to the official registry files.

### CODE REVIEW

**Comment by daoshengmu** [comment]
@Dexterp37 Please help review. I think we might need a data review for this change.

**Review by Dexterp37 — APPROVED** [review]

**Comment by daoshengmu** [comment]
# Request for data collection review form
 **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
 
 1. **What questions will you answer with this data?**
 In order to fix the metric names didn't match in #198, we need to do this adjustment.
 
 * distribution.fxr_channel_name: (it was distribution.channel_name) Determining which channel is Firefox Reality PC downloaded from.
 * distribution.ff_install_from: (it was distribution.install_from) Determining how users gets Firefox desktop for running with Firefox Reality. Firefox desktop could be embedded with FxR installer or users download it by their own.
 2. **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**
 
 *  Helping Mozilla understand how our product distributes to users and if Firefox Reality would be able to help Firefox desktop installs.
  
 3. **What alternative methods did you consider to answer these questions? Why were they not sufficient?**
 
 * N/A, we just replace the old names with correct metric names.
 
 4. **Can current instrumentation answer these questions?**
 
 * N/A, we just replace the old names with correct metric names.
 
 5. **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection](https://wiki.mozilla.org/Firefox/Data_Collection) [categories](https://wiki.mozilla.org/Firefox/Data_Collection#Data_Collection_Categories) on the found on the Mozilla wiki.**
 
 * distribution.fxr_channel_name: Category 2.
 * distribution.ff_install_from: Category 2.
 6. **How long will this data be collected?**
 
 Until 01/01/2021. We will extend the expiration date if we need.
 
 7. **What populations will you measure?**

 * All release, beta, and nightly users with telemetry enabled.
 
 8. **Please provide a general description of how you will analyze this data.**
 
 * [Glean](https://github.com/mozilla/glean)
 
 9. **Where do you intend to share the results of your analysis?**
 
 * Only on Glean and with Firefox Reality team.

The metrics documentation is [here](https://github.com/MozillaReality/FirefoxRealityPC/blob/27c057946022aea1ff26500069e788c1005ff4a1/docs/metrics.md).
We are according to `datareporting.healthreport.uploadEnabled` in pref.js from an user profile to choose if enabling or disabling our telemetry system.

@chutten Please help data review.

**Comment by chutten** [comment]
DATA COLLECTION REVIEW RESPONSE:

    Is there or will there be documentation that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes.

    Is there a control mechanism that allows the user to turn the data collection on and off?

Yes. This collection is can be controlled through Firefox Reality's Preferences.

    If the request is for permanent data collection, is there someone who will monitor the data over time?

No. This collection will expire Jan 1 2021.

    Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction.

    Is the data collection request for default-on or default-off?

Default on for all channels.

    Does the instrumentation include the addition of any new identifiers?

No.

    Is the data collection covered by the existing Firefox privacy notice?

Yes.

    Does there need to be a check-in in the future to determine whether to renew the data?

Yes. Daosheng is responsible for renewing or removing the collection before it expires 2021-01-01.

---
Result: datareview+

**Comment by daoshengmu** [comment]
@thomasmo Please help review, then we can merge it.

**Review by thomasmo — APPROVED** [review]
lgtm!

**Pull request merged**
